// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8yWhM0G-KMqwLhTcFm4q6mVht4N7e1gU',
    appId: '1:339886802859:web:70e83b91205993370fb4ee',
    messagingSenderId: '339886802859',
    projectId: 'fir-flutter-codelab-e6e51',
    authDomain: 'fir-flutter-codelab-e6e51.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-e6e51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECSksK-oqwt_re1G7IDm22-ayaXzPaGo',
    appId: '1:339886802859:android:e7b17de449e15dd50fb4ee',
    messagingSenderId: '339886802859',
    projectId: 'fir-flutter-codelab-e6e51',
    storageBucket: 'fir-flutter-codelab-e6e51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfFR43ujgQsRqWXwLWbzLjLbaVKWeUO64',
    appId: '1:339886802859:ios:57874c0c6a8fca5a0fb4ee',
    messagingSenderId: '339886802859',
    projectId: 'fir-flutter-codelab-e6e51',
    storageBucket: 'fir-flutter-codelab-e6e51.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfFR43ujgQsRqWXwLWbzLjLbaVKWeUO64',
    appId: '1:339886802859:ios:57874c0c6a8fca5a0fb4ee',
    messagingSenderId: '339886802859',
    projectId: 'fir-flutter-codelab-e6e51',
    storageBucket: 'fir-flutter-codelab-e6e51.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8yWhM0G-KMqwLhTcFm4q6mVht4N7e1gU',
    appId: '1:339886802859:web:8ed170a95ae2b5b00fb4ee',
    messagingSenderId: '339886802859',
    projectId: 'fir-flutter-codelab-e6e51',
    authDomain: 'fir-flutter-codelab-e6e51.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-e6e51.firebasestorage.app',
  );
}
